
services:
  # API service (FastAPI)
  diabetes_api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000

  # API service (FastAPI)
  diabetes_ui:
    build: .
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://diabetes_api:8000/predict
    command: python src/app/gradio_app.py
    depends_on:
      - diabetes_api