name: mlops311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - requests
  - pip:
      # additional lightweight packages that are OK to install via pip in the env
      - mlflow
      - gradio
      - fastapi
      - uvicorn
      - pydantic
      - python-dotenv
      - great_expectations
